# -*- coding: utf-8 -*-
"""cs289-final-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158xbr-CeFnFOWheWhJ5bcUygeipZrKik
"""

import os
import pandas as pd
from datasets import Dataset, Image, ClassLabel
import torch
from torch import nn
from torchvision.models import resnet50, ResNet50_Weights
from torch.optim import AdamW
import shutil

import kagglehub

# Download latest version
path = kagglehub.dataset_download("kmader/skin-cancer-mnist-ham10000")

metadata = pd.read_csv(path + "/HAM10000_metadata.csv")

metadata.head()

work_path = '/kaggle/working/skin-cancer-mnist-ham10000'
shutil.copytree(path + "/HAM10000_images_part_1", work_path + "/HAM10000_images", dirs_exist_ok=True)
shutil.copytree(path + "/HAM10000_images_part_2", work_path + "/HAM10000_images", dirs_exist_ok=True)
len(os.listdir(work_path + "/HAM10000_images"))

image_dir = work_path + "/HAM10000_images"
csv_path = path + "/HAM10000_metadata.csv"

df = pd.read_csv(csv_path)
df["image"] = df["image_id"].apply(lambda x: os.path.join(image_dir, x + ".jpg"))

labels = sorted(df["dx"].unique())
label_feature = ClassLabel(names=labels)

df["label"] = df["dx"].apply(lambda x: label_feature.str2int(x))

dataset = Dataset.from_pandas(df[["image", "label"]])
dataset = dataset.cast_column("image", Image())
dataset = dataset.cast_column("label", label_feature)

splits = dataset.train_test_split(test_size=0.2, stratify_by_column="label", seed=42)
train_ds = splits["train"]
val_ds = splits["test"]

num_classes = len(labels)

weights = ResNet50_Weights.DEFAULT
model = resnet50(weights=weights)

model.fc = nn.Linear(model.fc.in_features, num_classes)

preprocess = weights.transforms()

from torchvision import transforms

train_transform = transforms.Compose([
    transforms.RandomResizedCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(mean=weights.transforms().mean, std=weights.transforms().std),
])

eval_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=weights.transforms().mean, std=weights.transforms().std),
])

def train_tfms(batch):
    batch["pixel_values"] = [train_transform(img.convert("RGB")) for img in batch["image"]]
    return batch

def eval_tfms(batch):
    batch["pixel_values"] = [eval_transform(img.convert("RGB")) for img in batch["image"]]
    return batch

train_ds.set_transform(train_tfms)
val_ds.set_transform(eval_tfms)

from torch.utils.data import DataLoader

def collate_fn(batch):
    return {
        "pixel_values": torch.stack([x["pixel_values"] for x in batch]),
        "labels": torch.tensor([x["label"] for x in batch]),
    }

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, collate_fn=collate_fn)
val_loader = DataLoader(val_ds, batch_size=32, shuffle=False, collate_fn=collate_fn)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

for param in model.parameters():
    param.requires_grad = False

model.fc = nn.Linear(model.fc.in_features, num_classes)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = AdamW(model.fc.parameters(), lr=1e-3, weight_decay=1e-4)

def train_one_epoch(model, dataloader, optimizer, criterion, device):
    model.train()

    running_loss = 0.0
    correct = 0
    total = 0

    for batch in dataloader:
        images = batch["pixel_values"].to(device)
        labels_batch = batch["labels"].to(device)

        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels_batch)

        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)

        preds = outputs.argmax(dim=1)
        correct += (preds == labels_batch).sum().item()
        total += labels_batch.size(0)

    epoch_loss = running_loss / total
    epoch_acc = correct / total

    return epoch_loss, epoch_acc

def evaluate(model, dataloader, criterion, device):
    model.eval()

    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for batch in dataloader:
            images = batch["pixel_values"].to(device)
            labels_batch = batch["labels"].to(device)

            outputs = model(images)
            loss = criterion(outputs, labels_batch)

            running_loss += loss.item() * images.size(0)

            preds = outputs.argmax(dim=1)
            correct += (preds == labels_batch).sum().item()
            total += labels_batch.size(0)

    epoch_loss = running_loss / total
    epoch_acc = correct / total

    return epoch_loss, epoch_acc

num_epochs = 10
best_val_acc = 0.0

for epoch in range(num_epochs):
    train_loss, train_acc = train_one_epoch(
        model,
        train_loader,
        optimizer,
        criterion,
        device
    )

    val_loss, val_acc = evaluate(
        model,
        val_loader,
        criterion,
        device
    )

    print(
        f"Epoch {epoch+1}/{num_epochs} | "
        f"train loss: {train_loss:.4f}, train acc: {train_acc:.4f} | "
        f"val loss: {val_loss:.4f}, val acc: {val_acc:.4f}"
    )

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), "best_resnet.pt")
        print("Saved new best model")




















